const eventos = [
    // {nome:"Baú", qtdMax:2, chance:7, acao:bau_abrir()},
    // {nome:"NPC", qtdMax:1, chance:2, acao:npc_conversar()},
    // {nome:"Inimigo", qtdMax:2, chance:4, acao: inimigo_batalhar()},
]

const nomeItens = [
    "Espada da Chama Eterna",
    "Adaga Sombria",
    "Machado do Berserker",
    "Arco do Vento Cortante",
    "Cajado do Mago Supremo",
    "Escudo de Titânio",
    "Elmo do Dragão",
    "Botas da Agilidade",
    "Luvas do Assassino",
    "Amuleto da Vida Eterna",
    "Anel da Invisibilidade",
    "Manto das Sombras",
    "Bracelete da Força",
    "Cinturão de Gigante",
    "Colar da Sabedoria",
    "Pingente da Cura",
    "Poção de Mana",
    "Poção de Vida",
    "Flechas Infinitas",
    "Lança Relâmpago",
    "Martelo dos Deuses",
    "Espada do Destino",
    "Escudo da Luz",
    "Elmo do Conquistador",
    "Botas da Leveza",
    "Luvas da Destruição",
    "Adaga da Traição",
    "Machado de Guerra",
    "Arco da Caça",
    "Cajado do Fogo",
    "Manto do Invisível",
    "Anel da Proteção",
    "Amuleto do Tempo",
    "Bracelete do Poder",
    "Cinturão da Resistência",
    "Colar da Fortuna",
    "Pingente do Vigor",
    "Poção de Velocidade",
    "Poção de Resistência",
    "Flechas Venenosas",
    "Lança do Vento",
    "Martelo do Trovão",
    "Espada do Rei",
    "Escudo da Defesa",
    "Elmo do Guardião",
    "Botas da Velocidade",
    "Luvas da Fúria",
    "Adaga de Gelo",
    "Machado da Ruína",
    "Arco da Lua",
    "Cajado da Terra",
    "Manto da Noite",
    "Anel do Poder",
    "Amuleto do Guerreiro"
]